### ISSUE TITLE
Upload-Checksum is required, even though it should be optional

### ISSUE THREAD

**Issue by ntzm** [TCB13/thunder-tus-php#1]
Using `tus-js-client` on default settings, and Thunder TUS with S3, it throws a 400 on PATCH due to `Upload-Checksum` being required (Server.php line 299). Upload-Checksum should be optional according to the spec: https://tus.io/protocols/resumable-upload.html#checksum

**Comment by TCB13** [comment]
At this time that header is always required. I believe that if you're after TUS you must also be looking for  data integrity and that's the main reason why it is required.

**Comment by ntzm** [comment]
OK thanks
